---
- name: Fetch Packer
  ansible.builtin.command: "curl -fsSL -o /tmp/packer.zip https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
  args:
    creates: /tmp/packer.zip
  become: true


- name: Unpack Packer
  ansible.builtin.unarchive:
    src: /tmp/packer.zip
    dest: /tmp
    list_files: true
    remote_src: true

- name: Install Packer to /usr/local/bin/packer.io
  ansible.builtin.copy:
    src: /tmp/packer
    dest: /usr/local/bin/packer
    mode: 0755
    owner: root
    remote_src: true
  become: true
