---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install unzip
      package:
        name: unzip
        state: present
